#!/usr/bin/env python3

# repo at: https://github.com/not-louis-239/toolbox
# Copyright (C) 2026 Louis Masarei-Boulton <243234869+not-louis-239@users.noreply.github.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

try:
    proj_root = next(p for p in Path(__file__).parents if (p / ".git").exists())
except StopIteration:
    raise RuntimeError("Could not find repository root directory") from None
sys.path.insert(0, str(proj_root / "lib"))

from ansi_art.parse_args import parse_args, validate_args
from toolbox_lib.ansi_parse import load_ansi_from_img, serialise

def make_python_script(ansi_art: str) -> str:
    escaped: list[str] = list(
        ansi_art
        .replace('\033', '\\033')
        .splitlines()
    )

    return (
        f"# Generated by ansi_art @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        "escaped: tuple[str, ...] = (\n"
        + ",\n".join(f'    "{e}"' for e in escaped)
        + "\n)\n\n"
        + 'if __name__ == "__main__":\n'
        f'    print("\\n".join(escaped))\n'
    )

def main():
    args = parse_args()
    validate_args(args)

    ansi_art = load_ansi_from_img(args.input)
    serialised = serialise(ansi_art, mode=args.mode)
    py_script = make_python_script(serialised)
    args.output.write_text(py_script, encoding="utf-8")

    print(f"Script generation completed at '{args.output}'\n")
    print(serialised)

if __name__ == "__main__":
    main()
